spring:
  application:
    name: spring-gateway
  cloud:
    gateway:
      routes:
        - id: productos
          uri: lb://productos
          predicates:
            - Path=/api/productos/**
          filters:
            - StripPrefix=2
        - id: items
          uri: lb://items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: DEBUG

